package app.vazovsky.permaware.ui.theme

import androidx.compose.ui.graphics.Color

internal val Violet95 = Color(0xFFF3EFFE)
internal val Violet90 = Color(0xFFE6DDFC)
internal val Violet80 = Color(0xFFC9BAF6)
internal val Violet60 = Color(0xFF9B87E6)
internal val Violet50 = Color(0xFF6C5DD3)
internal val Violet40 = Color(0xFF5B4BC0)
internal val Violet30 = Color(0xFF45379A)
internal val Violet20 = Color(0xFF2E2560)

internal val LightBackground = Color(0xFFEDE7FD)
internal val LightSurface = Color(0xFFFCFBFE)
internal val LightElevated = Color(0xFFFFFFFF)
internal val LightSurfaceMuted = Color(0xFFE7DFFB)
internal val LightOnSurfaceMuted = Color(0xFF514873)
internal val LightBorder = Color(0xFFDCD3F1)
internal val LightDivider = Color(0xFFE7E2F3)
internal val LightTextPrimary = Color(0xFF1F1D2C)
internal val LightTextSecondary = Color(0xFF58556A)
internal val LightTextDisabled = Color(0xFF8E8B9B)

internal val DarkBackground = Color(0xFF0E0C1B)
internal val DarkSurface = Color(0xFF161523)
internal val DarkElevated = Color(0xFF23212F)
internal val DarkSurfaceMuted = Color(0xFF2C2A3C)
internal val DarkOnSurfaceMuted = Color(0xFFB9B2D5)
internal val DarkBorder = Color(0xFF363446)
internal val DarkDivider = Color(0xFF282735)
internal val DarkTextPrimary = Color(0xFFEEEDF5)
internal val DarkTextSecondary = Color(0xFF9897A3)
internal val DarkTextDisabled = Color(0xFF5D5C66)

internal val AttentionLowContainerLight = Color(0xFFE9E5F5)
internal val AttentionLowContentLight = Color(0xFF4B4370)
internal val AttentionLowSolidLight = Color(0xFF746D93)
internal val AttentionLowOnSolidLight = Color(0xFFFFFFFF)
internal val AttentionModerateContainerLight = Color(0xFFFFE7B0)
internal val AttentionModerateContentLight = Color(0xFF6B4500)
internal val AttentionModerateSolidLight = Color(0xFFF5A300)
internal val AttentionModerateOnSolidLight = Color(0xFF3B2800)
internal val AttentionElevatedContainerLight = Color(0xFFFFDBD8)
internal val AttentionElevatedContentLight = Color(0xFFB3121B)
internal val AttentionElevatedSolidLight = Color(0xFFD92D20)
internal val AttentionElevatedOnSolidLight = Color(0xFFFFFFFF)

internal val AttentionLowContainerDark = Color(0xFF2A2839)
internal val AttentionLowContentDark = Color(0xFFB9B2D5)
internal val AttentionLowSolidDark = Color(0xFF6E688A)
internal val AttentionLowOnSolidDark = Color(0xFFF0EEF7)
internal val AttentionModerateContainerDark = Color(0xFF4A3510)
internal val AttentionModerateContentDark = Color(0xFFFFCF70)
internal val AttentionModerateSolidDark = Color(0xFFFFB224)
internal val AttentionModerateOnSolidDark = Color(0xFF2E1F00)
internal val AttentionElevatedContainerDark = Color(0xFF55211F)
internal val AttentionElevatedContentDark = Color(0xFFFF9C96)
internal val AttentionElevatedSolidDark = Color(0xFFFF5A52)
internal val AttentionElevatedOnSolidDark = Color(0xFF450A08)

internal val PositiveLight = Color(0xFF00773B)
internal val PositiveDark = Color(0xFF51B67A)
internal val ErrorLight = Color(0xFFC51D28)
internal val ErrorDark = Color(0xFFF3625D)
internal val ErrorContainerLight = Color(0xFFFFE2DF)
internal val ErrorContainerDark = Color(0xFF47211E)
internal val OnErrorLight = Color(0xFFFFFFFF)
internal val OnErrorDark = Color(0xFF3A0A0A)

internal val ShadowViolet = Color(0xFF1E143C)
