package app.vazovsky.permaware.domain.permission

import androidx.annotation.StringRes
import app.vazovsky.permaware.R
import app.vazovsky.permaware.domain.model.PermissionCategory
import app.vazovsky.permaware.domain.model.Sensitivity

/**
 * Одна запись локальной базы знаний о разрешениях.
 *
 * [appOpGated] помечает разрешения, фактический доступ по которым решает запись в AppOps,
 * недоступная для сторонних пакетов. Для них состояние выдачи не угадывается, а сообщается как
 * [app.vazovsky.permaware.domain.model.PermissionState.UNDETERMINED].
 */
data class PermissionKnowledge(
    val permission: String,
    val category: PermissionCategory,
    val sensitivity: Sensitivity,
    val attentionWeight: Int,
    @param:StringRes val titleRes: Int,
    @param:StringRes val descriptionRes: Int,
    @param:StringRes val attentionRes: Int,
    val appOpGated: Boolean = false,
)

/**
 * Локальная офлайновая база знаний о разрешениях, которые PermAware умеет объяснить человеческим
 * языком.
 */
object PermissionCatalog {

    private const val P = "android.permission."

    val entries: Map<String, PermissionKnowledge> = listOf(
        PermissionKnowledge(
            permission = P + "ACCESS_FINE_LOCATION",
            category = PermissionCategory.LOCATION,
            sensitivity = Sensitivity.HIGH,
            attentionWeight = 12,
            titleRes = R.string.perm_access_fine_location_title,
            descriptionRes = R.string.perm_access_fine_location_desc,
            attentionRes = R.string.perm_access_fine_location_att,
        ),
        PermissionKnowledge(
            permission = P + "ACCESS_COARSE_LOCATION",
            category = PermissionCategory.LOCATION,
            sensitivity = Sensitivity.NOTABLE,
            attentionWeight = 6,
            titleRes = R.string.perm_access_coarse_location_title,
            descriptionRes = R.string.perm_access_coarse_location_desc,
            attentionRes = R.string.perm_access_coarse_location_att,
        ),
        PermissionKnowledge(
            permission = P + "ACCESS_BACKGROUND_LOCATION",
            category = PermissionCategory.LOCATION,
            sensitivity = Sensitivity.HIGH,
            attentionWeight = 20,
            titleRes = R.string.perm_access_background_location_title,
            descriptionRes = R.string.perm_access_background_location_desc,
            attentionRes = R.string.perm_access_background_location_att,
        ),
        PermissionKnowledge(
            permission = P + "ACCESS_MEDIA_LOCATION",
            category = PermissionCategory.LOCATION,
            sensitivity = Sensitivity.NOTABLE,
            attentionWeight = 4,
            titleRes = R.string.perm_access_media_location_title,
            descriptionRes = R.string.perm_access_media_location_desc,
            attentionRes = R.string.perm_access_media_location_att,
        ),
        PermissionKnowledge(
            permission = P + "CAMERA",
            category = PermissionCategory.CAMERA,
            sensitivity = Sensitivity.HIGH,
            attentionWeight = 14,
            titleRes = R.string.perm_camera_title,
            descriptionRes = R.string.perm_camera_desc,
            attentionRes = R.string.perm_camera_att,
        ),
        PermissionKnowledge(
            permission = P + "RECORD_AUDIO",
            category = PermissionCategory.MICROPHONE,
            sensitivity = Sensitivity.HIGH,
            attentionWeight = 14,
            titleRes = R.string.perm_record_audio_title,
            descriptionRes = R.string.perm_record_audio_desc,
            attentionRes = R.string.perm_record_audio_att,
        ),
        PermissionKnowledge(
            permission = P + "READ_CONTACTS",
            category = PermissionCategory.CONTACTS,
            sensitivity = Sensitivity.HIGH,
            attentionWeight = 10,
            titleRes = R.string.perm_read_contacts_title,
            descriptionRes = R.string.perm_read_contacts_desc,
            attentionRes = R.string.perm_read_contacts_att,
        ),
        PermissionKnowledge(
            permission = P + "WRITE_CONTACTS",
            category = PermissionCategory.CONTACTS,
            sensitivity = Sensitivity.NOTABLE,
            attentionWeight = 5,
            titleRes = R.string.perm_write_contacts_title,
            descriptionRes = R.string.perm_write_contacts_desc,
            attentionRes = R.string.perm_write_contacts_att,
        ),
        PermissionKnowledge(
            permission = P + "GET_ACCOUNTS",
            category = PermissionCategory.ACCOUNTS,
            sensitivity = Sensitivity.NOTABLE,
            attentionWeight = 5,
            titleRes = R.string.perm_get_accounts_title,
            descriptionRes = R.string.perm_get_accounts_desc,
            attentionRes = R.string.perm_get_accounts_att,
        ),
        PermissionKnowledge(
            permission = P + "READ_CALENDAR",
            category = PermissionCategory.CALENDAR,
            sensitivity = Sensitivity.NOTABLE,
            attentionWeight = 7,
            titleRes = R.string.perm_read_calendar_title,
            descriptionRes = R.string.perm_read_calendar_desc,
            attentionRes = R.string.perm_read_calendar_att,
        ),
        PermissionKnowledge(
            permission = P + "WRITE_CALENDAR",
            category = PermissionCategory.CALENDAR,
            sensitivity = Sensitivity.NOTABLE,
            attentionWeight = 4,
            titleRes = R.string.perm_write_calendar_title,
            descriptionRes = R.string.perm_write_calendar_desc,
            attentionRes = R.string.perm_write_calendar_att,
        ),
        PermissionKnowledge(
            permission = P + "READ_SMS",
            category = PermissionCategory.SMS,
            sensitivity = Sensitivity.HIGH,
            attentionWeight = 14,
            titleRes = R.string.perm_read_sms_title,
            descriptionRes = R.string.perm_read_sms_desc,
            attentionRes = R.string.perm_read_sms_att,
        ),
        PermissionKnowledge(
            permission = P + "SEND_SMS",
            category = PermissionCategory.SMS,
            sensitivity = Sensitivity.HIGH,
            attentionWeight = 12,
            titleRes = R.string.perm_send_sms_title,
            descriptionRes = R.string.perm_send_sms_desc,
            attentionRes = R.string.perm_send_sms_att,
        ),
        PermissionKnowledge(
            permission = P + "RECEIVE_SMS",
            category = PermissionCategory.SMS,
            sensitivity = Sensitivity.HIGH,
            attentionWeight = 12,
            titleRes = R.string.perm_receive_sms_title,
            descriptionRes = R.string.perm_receive_sms_desc,
            attentionRes = R.string.perm_receive_sms_att,
        ),
        PermissionKnowledge(
            permission = P + "RECEIVE_MMS",
            category = PermissionCategory.SMS,
            sensitivity = Sensitivity.NOTABLE,
            attentionWeight = 6,
            titleRes = R.string.perm_receive_mms_title,
            descriptionRes = R.string.perm_receive_mms_desc,
            attentionRes = R.string.perm_receive_mms_att,
        ),
        PermissionKnowledge(
            permission = P + "RECEIVE_WAP_PUSH",
            category = PermissionCategory.SMS,
            sensitivity = Sensitivity.NOTABLE,
            attentionWeight = 5,
            titleRes = R.string.perm_receive_wap_push_title,
            descriptionRes = R.string.perm_receive_wap_push_desc,
            attentionRes = R.string.perm_receive_wap_push_att,
        ),
        PermissionKnowledge(
            permission = P + "READ_CELL_BROADCASTS",
            category = PermissionCategory.SMS,
            sensitivity = Sensitivity.NONE,
            attentionWeight = 0,
            titleRes = R.string.perm_read_cell_broadcasts_title,
            descriptionRes = R.string.perm_read_cell_broadcasts_desc,
            attentionRes = R.string.perm_read_cell_broadcasts_att,
        ),
        PermissionKnowledge(
            permission = P + "READ_PHONE_STATE",
            category = PermissionCategory.PHONE,
            sensitivity = Sensitivity.NOTABLE,
            attentionWeight = 7,
            titleRes = R.string.perm_read_phone_state_title,
            descriptionRes = R.string.perm_read_phone_state_desc,
            attentionRes = R.string.perm_read_phone_state_att,
        ),
        PermissionKnowledge(
            permission = P + "READ_PHONE_NUMBERS",
            category = PermissionCategory.PHONE,
            sensitivity = Sensitivity.NOTABLE,
            attentionWeight = 7,
            titleRes = R.string.perm_read_phone_numbers_title,
            descriptionRes = R.string.perm_read_phone_numbers_desc,
            attentionRes = R.string.perm_read_phone_numbers_att,
        ),
        PermissionKnowledge(
            permission = P + "CALL_PHONE",
            category = PermissionCategory.PHONE,
            sensitivity = Sensitivity.NOTABLE,
            attentionWeight = 8,
            titleRes = R.string.perm_call_phone_title,
            descriptionRes = R.string.perm_call_phone_desc,
            attentionRes = R.string.perm_call_phone_att,
        ),
        PermissionKnowledge(
            permission = P + "ANSWER_PHONE_CALLS",
            category = PermissionCategory.PHONE,
            sensitivity = Sensitivity.NOTABLE,
            attentionWeight = 6,
            titleRes = R.string.perm_answer_phone_calls_title,
            descriptionRes = R.string.perm_answer_phone_calls_desc,
            attentionRes = R.string.perm_answer_phone_calls_att,
        ),
        PermissionKnowledge(
            permission = P + "ADD_VOICEMAIL",
            category = PermissionCategory.PHONE,
            sensitivity = Sensitivity.NONE,
            attentionWeight = 0,
            titleRes = R.string.perm_add_voicemail_title,
            descriptionRes = R.string.perm_add_voicemail_desc,
            attentionRes = R.string.perm_add_voicemail_att,
        ),
        PermissionKnowledge(
            permission = P + "USE_SIP",
            category = PermissionCategory.PHONE,
            sensitivity = Sensitivity.NONE,
            attentionWeight = 0,
            titleRes = R.string.perm_use_sip_title,
            descriptionRes = R.string.perm_use_sip_desc,
            attentionRes = R.string.perm_use_sip_att,
        ),
        PermissionKnowledge(
            permission = P + "ACCEPT_HANDOVER",
            category = PermissionCategory.PHONE,
            sensitivity = Sensitivity.NONE,
            attentionWeight = 0,
            titleRes = R.string.perm_accept_handover_title,
            descriptionRes = R.string.perm_accept_handover_desc,
            attentionRes = R.string.perm_accept_handover_att,
        ),
        PermissionKnowledge(
            permission = P + "MANAGE_OWN_CALLS",
            category = PermissionCategory.PHONE,
            sensitivity = Sensitivity.NONE,
            attentionWeight = 0,
            titleRes = R.string.perm_manage_own_calls_title,
            descriptionRes = R.string.perm_manage_own_calls_desc,
            attentionRes = R.string.perm_manage_own_calls_att,
        ),
        PermissionKnowledge(
            permission = P + "READ_CALL_LOG",
            category = PermissionCategory.CALL_LOG,
            sensitivity = Sensitivity.HIGH,
            attentionWeight = 12,
            titleRes = R.string.perm_read_call_log_title,
            descriptionRes = R.string.perm_read_call_log_desc,
            attentionRes = R.string.perm_read_call_log_att,
        ),
        PermissionKnowledge(
            permission = P + "WRITE_CALL_LOG",
            category = PermissionCategory.CALL_LOG,
            sensitivity = Sensitivity.NOTABLE,
            attentionWeight = 6,
            titleRes = R.string.perm_write_call_log_title,
            descriptionRes = R.string.perm_write_call_log_desc,
            attentionRes = R.string.perm_write_call_log_att,
        ),
        PermissionKnowledge(
            permission = P + "PROCESS_OUTGOING_CALLS",
            category = PermissionCategory.CALL_LOG,
            sensitivity = Sensitivity.NOTABLE,
            attentionWeight = 8,
            titleRes = R.string.perm_process_outgoing_calls_title,
            descriptionRes = R.string.perm_process_outgoing_calls_desc,
            attentionRes = R.string.perm_process_outgoing_calls_att,
        ),
        PermissionKnowledge(
            permission = P + "READ_EXTERNAL_STORAGE",
            category = PermissionCategory.STORAGE,
            sensitivity = Sensitivity.NOTABLE,
            attentionWeight = 8,
            titleRes = R.string.perm_read_external_storage_title,
            descriptionRes = R.string.perm_read_external_storage_desc,
            attentionRes = R.string.perm_read_external_storage_att,
        ),
        PermissionKnowledge(
            permission = P + "WRITE_EXTERNAL_STORAGE",
            category = PermissionCategory.STORAGE,
            sensitivity = Sensitivity.NOTABLE,
            attentionWeight = 6,
            titleRes = R.string.perm_write_external_storage_title,
            descriptionRes = R.string.perm_write_external_storage_desc,
            attentionRes = R.string.perm_write_external_storage_att,
        ),
        PermissionKnowledge(
            permission = P + "READ_MEDIA_IMAGES",
            category = PermissionCategory.STORAGE,
            sensitivity = Sensitivity.NOTABLE,
            attentionWeight = 8,
            titleRes = R.string.perm_read_media_images_title,
            descriptionRes = R.string.perm_read_media_images_desc,
            attentionRes = R.string.perm_read_media_images_att,
        ),
        PermissionKnowledge(
            permission = P + "READ_MEDIA_VIDEO",
            category = PermissionCategory.STORAGE,
            sensitivity = Sensitivity.NOTABLE,
            attentionWeight = 8,
            titleRes = R.string.perm_read_media_video_title,
            descriptionRes = R.string.perm_read_media_video_desc,
            attentionRes = R.string.perm_read_media_video_att,
        ),
        PermissionKnowledge(
            permission = P + "READ_MEDIA_AUDIO",
            category = PermissionCategory.STORAGE,
            sensitivity = Sensitivity.NOTABLE,
            attentionWeight = 4,
            titleRes = R.string.perm_read_media_audio_title,
            descriptionRes = R.string.perm_read_media_audio_desc,
            attentionRes = R.string.perm_read_media_audio_att,
        ),
        PermissionKnowledge(
            permission = P + "READ_MEDIA_VISUAL_USER_SELECTED",
            category = PermissionCategory.STORAGE,
            sensitivity = Sensitivity.NONE,
            attentionWeight = 0,
            titleRes = R.string.perm_read_media_visual_user_selected_title,
            descriptionRes = R.string.perm_read_media_visual_user_selected_desc,
            attentionRes = R.string.perm_read_media_visual_user_selected_att,
        ),
        PermissionKnowledge(
            permission = P + "MANAGE_MEDIA",
            category = PermissionCategory.STORAGE,
            sensitivity = Sensitivity.NOTABLE,
            attentionWeight = 6,
            titleRes = R.string.perm_manage_media_title,
            descriptionRes = R.string.perm_manage_media_desc,
            attentionRes = R.string.perm_manage_media_att,
            appOpGated = true,
        ),
        PermissionKnowledge(
            permission = P + "BODY_SENSORS",
            category = PermissionCategory.SENSORS,
            sensitivity = Sensitivity.NOTABLE,
            attentionWeight = 9,
            titleRes = R.string.perm_body_sensors_title,
            descriptionRes = R.string.perm_body_sensors_desc,
            attentionRes = R.string.perm_body_sensors_att,
        ),
        PermissionKnowledge(
            permission = P + "BODY_SENSORS_BACKGROUND",
            category = PermissionCategory.SENSORS,
            sensitivity = Sensitivity.HIGH,
            attentionWeight = 14,
            titleRes = R.string.perm_body_sensors_background_title,
            descriptionRes = R.string.perm_body_sensors_background_desc,
            attentionRes = R.string.perm_body_sensors_background_att,
        ),
        PermissionKnowledge(
            permission = P + "ACTIVITY_RECOGNITION",
            category = PermissionCategory.ACTIVITY,
            sensitivity = Sensitivity.NOTABLE,
            attentionWeight = 5,
            titleRes = R.string.perm_activity_recognition_title,
            descriptionRes = R.string.perm_activity_recognition_desc,
            attentionRes = R.string.perm_activity_recognition_att,
        ),
        PermissionKnowledge(
            permission = P + "BLUETOOTH_SCAN",
            category = PermissionCategory.NEARBY,
            sensitivity = Sensitivity.NOTABLE,
            attentionWeight = 6,
            titleRes = R.string.perm_bluetooth_scan_title,
            descriptionRes = R.string.perm_bluetooth_scan_desc,
            attentionRes = R.string.perm_bluetooth_scan_att,
        ),
        PermissionKnowledge(
            permission = P + "BLUETOOTH_CONNECT",
            category = PermissionCategory.NEARBY,
            sensitivity = Sensitivity.NOTABLE,
            attentionWeight = 4,
            titleRes = R.string.perm_bluetooth_connect_title,
            descriptionRes = R.string.perm_bluetooth_connect_desc,
            attentionRes = R.string.perm_bluetooth_connect_att,
        ),
        PermissionKnowledge(
            permission = P + "BLUETOOTH_ADVERTISE",
            category = PermissionCategory.NEARBY,
            sensitivity = Sensitivity.NONE,
            attentionWeight = 0,
            titleRes = R.string.perm_bluetooth_advertise_title,
            descriptionRes = R.string.perm_bluetooth_advertise_desc,
            attentionRes = R.string.perm_bluetooth_advertise_att,
        ),
        PermissionKnowledge(
            permission = P + "NEARBY_WIFI_DEVICES",
            category = PermissionCategory.NEARBY,
            sensitivity = Sensitivity.NOTABLE,
            attentionWeight = 5,
            titleRes = R.string.perm_nearby_wifi_devices_title,
            descriptionRes = R.string.perm_nearby_wifi_devices_desc,
            attentionRes = R.string.perm_nearby_wifi_devices_att,
        ),
        PermissionKnowledge(
            permission = P + "UWB_RANGING",
            category = PermissionCategory.NEARBY,
            sensitivity = Sensitivity.NONE,
            attentionWeight = 0,
            titleRes = R.string.perm_uwb_ranging_title,
            descriptionRes = R.string.perm_uwb_ranging_desc,
            attentionRes = R.string.perm_uwb_ranging_att,
        ),
        PermissionKnowledge(
            permission = P + "POST_NOTIFICATIONS",
            category = PermissionCategory.NOTIFICATIONS,
            sensitivity = Sensitivity.NONE,
            attentionWeight = 0,
            titleRes = R.string.perm_post_notifications_title,
            descriptionRes = R.string.perm_post_notifications_desc,
            attentionRes = R.string.perm_post_notifications_att,
        ),
        PermissionKnowledge(
            permission = P + "ACCESS_NOTIFICATION_POLICY",
            category = PermissionCategory.NOTIFICATIONS,
            sensitivity = Sensitivity.NOTABLE,
            attentionWeight = 4,
            titleRes = R.string.perm_access_notification_policy_title,
            descriptionRes = R.string.perm_access_notification_policy_desc,
            attentionRes = R.string.perm_access_notification_policy_att,
        ),
        PermissionKnowledge(
            permission = P + "SYSTEM_ALERT_WINDOW",
            category = PermissionCategory.SPECIAL_ACCESS,
            sensitivity = Sensitivity.HIGH,
            attentionWeight = 14,
            titleRes = R.string.perm_system_alert_window_title,
            descriptionRes = R.string.perm_system_alert_window_desc,
            attentionRes = R.string.perm_system_alert_window_att,
            appOpGated = true,
        ),
        PermissionKnowledge(
            permission = P + "REQUEST_INSTALL_PACKAGES",
            category = PermissionCategory.SPECIAL_ACCESS,
            sensitivity = Sensitivity.HIGH,
            attentionWeight = 18,
            titleRes = R.string.perm_request_install_packages_title,
            descriptionRes = R.string.perm_request_install_packages_desc,
            attentionRes = R.string.perm_request_install_packages_att,
            appOpGated = true,
        ),
        PermissionKnowledge(
            permission = P + "PACKAGE_USAGE_STATS",
            category = PermissionCategory.SPECIAL_ACCESS,
            sensitivity = Sensitivity.HIGH,
            attentionWeight = 14,
            titleRes = R.string.perm_package_usage_stats_title,
            descriptionRes = R.string.perm_package_usage_stats_desc,
            attentionRes = R.string.perm_package_usage_stats_att,
            appOpGated = true,
        ),
        PermissionKnowledge(
            permission = P + "MANAGE_EXTERNAL_STORAGE",
            category = PermissionCategory.SPECIAL_ACCESS,
            sensitivity = Sensitivity.HIGH,
            attentionWeight = 16,
            titleRes = R.string.perm_manage_external_storage_title,
            descriptionRes = R.string.perm_manage_external_storage_desc,
            attentionRes = R.string.perm_manage_external_storage_att,
            appOpGated = true,
        ),
        PermissionKnowledge(
            permission = P + "WRITE_SETTINGS",
            category = PermissionCategory.SPECIAL_ACCESS,
            sensitivity = Sensitivity.NOTABLE,
            attentionWeight = 9,
            titleRes = R.string.perm_write_settings_title,
            descriptionRes = R.string.perm_write_settings_desc,
            attentionRes = R.string.perm_write_settings_att,
            appOpGated = true,
        ),
        PermissionKnowledge(
            permission = P + "SCHEDULE_EXACT_ALARM",
            category = PermissionCategory.SPECIAL_ACCESS,
            sensitivity = Sensitivity.NOTABLE,
            attentionWeight = 5,
            titleRes = R.string.perm_schedule_exact_alarm_title,
            descriptionRes = R.string.perm_schedule_exact_alarm_desc,
            attentionRes = R.string.perm_schedule_exact_alarm_att,
            appOpGated = true,
        ),
        PermissionKnowledge(
            permission = P + "USE_EXACT_ALARM",
            category = PermissionCategory.SPECIAL_ACCESS,
            sensitivity = Sensitivity.NOTABLE,
            attentionWeight = 4,
            titleRes = R.string.perm_use_exact_alarm_title,
            descriptionRes = R.string.perm_use_exact_alarm_desc,
            attentionRes = R.string.perm_use_exact_alarm_att,
        ),
        PermissionKnowledge(
            permission = P + "BIND_ACCESSIBILITY_SERVICE",
            category = PermissionCategory.SPECIAL_ACCESS,
            sensitivity = Sensitivity.HIGH,
            attentionWeight = 0,
            titleRes = R.string.perm_bind_accessibility_service_title,
            descriptionRes = R.string.perm_bind_accessibility_service_desc,
            attentionRes = R.string.perm_bind_accessibility_service_att,
        ),
        PermissionKnowledge(
            permission = P + "BIND_NOTIFICATION_LISTENER_SERVICE",
            category = PermissionCategory.SPECIAL_ACCESS,
            sensitivity = Sensitivity.HIGH,
            attentionWeight = 0,
            titleRes = R.string.perm_bind_notification_listener_service_title,
            descriptionRes = R.string.perm_bind_notification_listener_service_desc,
            attentionRes = R.string.perm_bind_notification_listener_service_att,
        ),
        PermissionKnowledge(
            permission = P + "BIND_VPN_SERVICE",
            category = PermissionCategory.SPECIAL_ACCESS,
            sensitivity = Sensitivity.HIGH,
            attentionWeight = 0,
            titleRes = R.string.perm_bind_vpn_service_title,
            descriptionRes = R.string.perm_bind_vpn_service_desc,
            attentionRes = R.string.perm_bind_vpn_service_att,
        ),
        PermissionKnowledge(
            permission = P + "BIND_DEVICE_ADMIN",
            category = PermissionCategory.SPECIAL_ACCESS,
            sensitivity = Sensitivity.HIGH,
            attentionWeight = 0,
            titleRes = R.string.perm_bind_device_admin_title,
            descriptionRes = R.string.perm_bind_device_admin_desc,
            attentionRes = R.string.perm_bind_device_admin_att,
        ),
        PermissionKnowledge(
            permission = P + "REQUEST_IGNORE_BATTERY_OPTIMIZATIONS",
            category = PermissionCategory.SPECIAL_ACCESS,
            sensitivity = Sensitivity.NOTABLE,
            attentionWeight = 4,
            titleRes = R.string.perm_request_ignore_battery_optimizations_title,
            descriptionRes = R.string.perm_request_ignore_battery_optimizations_desc,
            attentionRes = R.string.perm_request_ignore_battery_optimizations_att,
        ),
        PermissionKnowledge(
            permission = P + "QUERY_ALL_PACKAGES",
            category = PermissionCategory.SPECIAL_ACCESS,
            sensitivity = Sensitivity.NOTABLE,
            attentionWeight = 5,
            titleRes = R.string.perm_query_all_packages_title,
            descriptionRes = R.string.perm_query_all_packages_desc,
            attentionRes = R.string.perm_query_all_packages_att,
        ),
        PermissionKnowledge(
            permission = P + "FOREGROUND_SERVICE_CAMERA",
            category = PermissionCategory.CAMERA,
            sensitivity = Sensitivity.NOTABLE,
            attentionWeight = 6,
            titleRes = R.string.perm_foreground_service_camera_title,
            descriptionRes = R.string.perm_foreground_service_camera_desc,
            attentionRes = R.string.perm_foreground_service_camera_att,
        ),
        PermissionKnowledge(
            permission = P + "FOREGROUND_SERVICE_MICROPHONE",
            category = PermissionCategory.MICROPHONE,
            sensitivity = Sensitivity.NOTABLE,
            attentionWeight = 6,
            titleRes = R.string.perm_foreground_service_microphone_title,
            descriptionRes = R.string.perm_foreground_service_microphone_desc,
            attentionRes = R.string.perm_foreground_service_microphone_att,
        ),
        PermissionKnowledge(
            permission = P + "FOREGROUND_SERVICE_LOCATION",
            category = PermissionCategory.LOCATION,
            sensitivity = Sensitivity.NOTABLE,
            attentionWeight = 6,
            titleRes = R.string.perm_foreground_service_location_title,
            descriptionRes = R.string.perm_foreground_service_location_desc,
            attentionRes = R.string.perm_foreground_service_location_att,
        ),
        PermissionKnowledge(
            permission = P + "FOREGROUND_SERVICE_HEALTH",
            category = PermissionCategory.SENSORS,
            sensitivity = Sensitivity.NOTABLE,
            attentionWeight = 4,
            titleRes = R.string.perm_foreground_service_health_title,
            descriptionRes = R.string.perm_foreground_service_health_desc,
            attentionRes = R.string.perm_foreground_service_health_att,
        ),
        PermissionKnowledge(
            permission = P + "RECEIVE_BOOT_COMPLETED",
            category = PermissionCategory.SYSTEM,
            sensitivity = Sensitivity.NONE,
            attentionWeight = 0,
            titleRes = R.string.perm_receive_boot_completed_title,
            descriptionRes = R.string.perm_receive_boot_completed_desc,
            attentionRes = R.string.perm_receive_boot_completed_att,
        ),
        PermissionKnowledge(
            permission = P + "INTERNET",
            category = PermissionCategory.SYSTEM,
            sensitivity = Sensitivity.NONE,
            attentionWeight = 0,
            titleRes = R.string.perm_internet_title,
            descriptionRes = R.string.perm_internet_desc,
            attentionRes = R.string.perm_internet_att,
        ),
        PermissionKnowledge(
            permission = P + "READ_MEDIA_VISUAL",
            category = PermissionCategory.STORAGE,
            sensitivity = Sensitivity.NONE,
            attentionWeight = 0,
            titleRes = R.string.perm_read_media_visual_title,
            descriptionRes = R.string.perm_read_media_visual_desc,
            attentionRes = R.string.perm_read_media_visual_att,
        ),
    ).associateBy { it.permission }

    fun find(permission: String): PermissionKnowledge? = entries[permission]

    fun isKnown(permission: String): Boolean = entries.containsKey(permission)

    fun permissionsOf(category: PermissionCategory): List<String> =
        entries.values.filter { it.category == category }.map { it.permission }
    val headlineCategories: List<PermissionCategory> = listOf(
        PermissionCategory.LOCATION,
        PermissionCategory.CAMERA,
        PermissionCategory.MICROPHONE,
        PermissionCategory.CONTACTS,
        PermissionCategory.SMS,
        PermissionCategory.STORAGE,
    )
}
